services:
  webos-bot:
    image: littleorange666/webos_alarm:1.0.0
    restart: on-failure
    environment:
      - TV_IP=${TV_IP}
      - TV_KEY=${TV_KEY}
      - YT_TARGET=${YT_TARGET}
      - DC_TOKEN=${DC_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"